// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlitegen

import (
	"database/sql"
)

type Project struct {
	ID              string
	DisplayName     string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	MetadataJson    string
}

type RuntimeLease struct {
	ID               string
	SessionID        string
	ClientID         string
	RequestID        string
	CreatedAtUnixMs  int64
	AcquiredAtUnixMs int64
	MetadataJson     string
}

type Session struct {
	ID                 string
	ProjectID          string
	WorkspaceID        string
	WorktreeID         sql.NullString
	ArtifactRelpath    string
	Name               string
	FirstPromptPreview string
	InputDraft         string
	ParentSessionID    string
	CreatedAtUnixMs    int64
	UpdatedAtUnixMs    int64
	LastSequence       int64
	ModelRequestCount  int64
	InFlightStep       int64
	AgentsInjected     int64
	CwdRelpath         string
	ContinuationJson   string
	LockedJson         string
	UsageStateJson     string
	MetadataJson       string
	LaunchVisible      int64
}

type Workspace struct {
	ID                string
	ProjectID         string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsPrimary         int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
}

type Worktree struct {
	ID                string
	WorkspaceID       string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsMain            int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
	BuilderManaged    int64
	CreatedBranch     int64
	OriginSessionID   string
}
