// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const deleteProjectIfOrphaned = `-- name: DeleteProjectIfOrphaned :execrows
DELETE FROM projects
WHERE id = ?1
  AND NOT EXISTS (
    SELECT 1
    FROM workspaces
    WHERE workspaces.project_id = projects.id
  )
`

func (q *Queries) DeleteProjectIfOrphaned(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectIfOrphaned, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProjectSummary = `-- name: GetProjectSummary :one
SELECT
    p.id,
    p.display_name,
    w.canonical_root_path AS root_path,
    CAST(COALESCE(COUNT(s.id), 0) AS INTEGER) AS session_count,
    COALESCE(MAX(s.updated_at_unix_ms), p.updated_at_unix_ms) AS latest_activity_unix_ms
FROM projects p
JOIN workspaces w ON w.project_id = p.id AND w.is_primary = 1
LEFT JOIN sessions s ON s.project_id = p.id AND s.launch_visible <> 0
WHERE p.id = ?1
GROUP BY p.id, p.display_name, w.canonical_root_path, p.updated_at_unix_ms
LIMIT 1
`

type GetProjectSummaryRow struct {
	ID                   string
	DisplayName          string
	RootPath             string
	SessionCount         int64
	LatestActivityUnixMs int64
}

func (q *Queries) GetProjectSummary(ctx context.Context, projectID string) (GetProjectSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectSummary, projectID)
	var i GetProjectSummaryRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.RootPath,
		&i.SessionCount,
		&i.LatestActivityUnixMs,
	)
	return i, err
}

const getRuntimeLeaseByID = `-- name: GetRuntimeLeaseByID :one
SELECT
    id,
    session_id,
    client_id,
    request_id,
    state,
    created_at_unix_ms,
    acquired_at_unix_ms,
    released_at_unix_ms,
    expires_at_unix_ms,
    metadata_json
FROM runtime_leases
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetRuntimeLeaseByID(ctx context.Context, leaseID string) (RuntimeLease, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeLeaseByID, leaseID)
	var i RuntimeLease
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ClientID,
		&i.RequestID,
		&i.State,
		&i.CreatedAtUnixMs,
		&i.AcquiredAtUnixMs,
		&i.ReleasedAtUnixMs,
		&i.ExpiresAtUnixMs,
		&i.MetadataJson,
	)
	return i, err
}

const getSessionExecutionTargetByID = `-- name: GetSessionExecutionTargetByID :one
SELECT
    s.id AS session_id,
    s.project_id,
    s.workspace_id,
    w.display_name AS workspace_name,
    w.canonical_root_path AS workspace_root,
    w.availability AS workspace_availability,
    s.worktree_id,
    COALESCE(wt.display_name, '') AS worktree_name,
    COALESCE(wt.canonical_root_path, '') AS worktree_root,
    COALESCE(wt.availability, '') AS worktree_availability,
    s.cwd_relpath
FROM sessions s
JOIN workspaces w ON w.id = s.workspace_id
LEFT JOIN worktrees wt ON wt.id = s.worktree_id
WHERE s.id = ?1
LIMIT 1
`

type GetSessionExecutionTargetByIDRow struct {
	SessionID             string
	ProjectID             string
	WorkspaceID           string
	WorkspaceName         string
	WorkspaceRoot         string
	WorkspaceAvailability string
	WorktreeID            sql.NullString
	WorktreeName          string
	WorktreeRoot          string
	WorktreeAvailability  string
	CwdRelpath            string
}

func (q *Queries) GetSessionExecutionTargetByID(ctx context.Context, sessionID string) (GetSessionExecutionTargetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionExecutionTargetByID, sessionID)
	var i GetSessionExecutionTargetByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.ProjectID,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.WorkspaceRoot,
		&i.WorkspaceAvailability,
		&i.WorktreeID,
		&i.WorktreeName,
		&i.WorktreeRoot,
		&i.WorktreeAvailability,
		&i.CwdRelpath,
	)
	return i, err
}

const getSessionRecordByID = `-- name: GetSessionRecordByID :one
SELECT
    s.id,
    s.artifact_relpath,
    s.name,
    s.first_prompt_preview,
    s.input_draft,
    s.parent_session_id,
    s.created_at_unix_ms,
    s.updated_at_unix_ms,
    s.last_sequence,
    s.model_request_count,
    s.in_flight_step,
    s.agents_injected,
    s.continuation_json,
    s.locked_json,
    s.usage_state_json,
    s.metadata_json,
    w.canonical_root_path AS workspace_root
FROM sessions s
JOIN workspaces w ON w.id = s.workspace_id
WHERE s.id = ?1
LIMIT 1
`

type GetSessionRecordByIDRow struct {
	ID                 string
	ArtifactRelpath    string
	Name               string
	FirstPromptPreview string
	InputDraft         string
	ParentSessionID    string
	CreatedAtUnixMs    int64
	UpdatedAtUnixMs    int64
	LastSequence       int64
	ModelRequestCount  int64
	InFlightStep       int64
	AgentsInjected     int64
	ContinuationJson   string
	LockedJson         string
	UsageStateJson     string
	MetadataJson       string
	WorkspaceRoot      string
}

func (q *Queries) GetSessionRecordByID(ctx context.Context, sessionID string) (GetSessionRecordByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionRecordByID, sessionID)
	var i GetSessionRecordByIDRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactRelpath,
		&i.Name,
		&i.FirstPromptPreview,
		&i.InputDraft,
		&i.ParentSessionID,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
		&i.LastSequence,
		&i.ModelRequestCount,
		&i.InFlightStep,
		&i.AgentsInjected,
		&i.ContinuationJson,
		&i.LockedJson,
		&i.UsageStateJson,
		&i.MetadataJson,
		&i.WorkspaceRoot,
	)
	return i, err
}

const getWorkspaceBindingByCanonicalRoot = `-- name: GetWorkspaceBindingByCanonicalRoot :one
SELECT
    p.id AS project_id,
    p.display_name AS project_display_name,
    w.id AS workspace_id,
    w.canonical_root_path AS workspace_root
FROM workspaces w
JOIN projects p ON p.id = w.project_id
WHERE w.canonical_root_path = ?1
LIMIT 1
`

type GetWorkspaceBindingByCanonicalRootRow struct {
	ProjectID          string
	ProjectDisplayName string
	WorkspaceID        string
	WorkspaceRoot      string
}

func (q *Queries) GetWorkspaceBindingByCanonicalRoot(ctx context.Context, canonicalRootPath string) (GetWorkspaceBindingByCanonicalRootRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBindingByCanonicalRoot, canonicalRootPath)
	var i GetWorkspaceBindingByCanonicalRootRow
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectDisplayName,
		&i.WorkspaceID,
		&i.WorkspaceRoot,
	)
	return i, err
}

const insertRuntimeLease = `-- name: InsertRuntimeLease :exec
INSERT INTO runtime_leases (
    id,
    session_id,
    client_id,
    request_id,
    state,
    created_at_unix_ms,
    acquired_at_unix_ms,
    released_at_unix_ms,
    expires_at_unix_ms,
    metadata_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type InsertRuntimeLeaseParams struct {
	ID               string
	SessionID        string
	ClientID         string
	RequestID        string
	State            string
	CreatedAtUnixMs  int64
	AcquiredAtUnixMs int64
	ReleasedAtUnixMs int64
	ExpiresAtUnixMs  int64
	MetadataJson     string
}

func (q *Queries) InsertRuntimeLease(ctx context.Context, arg InsertRuntimeLeaseParams) error {
	_, err := q.db.ExecContext(ctx, insertRuntimeLease,
		arg.ID,
		arg.SessionID,
		arg.ClientID,
		arg.RequestID,
		arg.State,
		arg.CreatedAtUnixMs,
		arg.AcquiredAtUnixMs,
		arg.ReleasedAtUnixMs,
		arg.ExpiresAtUnixMs,
		arg.MetadataJson,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.display_name,
    w.canonical_root_path AS root_path,
    CAST(COALESCE(COUNT(s.id), 0) AS INTEGER) AS session_count,
    COALESCE(MAX(s.updated_at_unix_ms), p.updated_at_unix_ms) AS latest_activity_unix_ms
FROM projects p
JOIN workspaces w ON w.project_id = p.id AND w.is_primary = 1
LEFT JOIN sessions s ON s.project_id = p.id AND s.launch_visible <> 0
GROUP BY p.id, p.display_name, w.canonical_root_path, p.updated_at_unix_ms
ORDER BY latest_activity_unix_ms DESC
`

type ListProjectsRow struct {
	ID                   string
	DisplayName          string
	RootPath             string
	SessionCount         int64
	LatestActivityUnixMs int64
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.RootPath,
			&i.SessionCount,
			&i.LatestActivityUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT
    id,
    name,
    first_prompt_preview,
    updated_at_unix_ms
FROM sessions
WHERE project_id = ?1
  AND launch_visible <> 0
ORDER BY updated_at_unix_ms DESC, rowid DESC
`

type ListSessionsByProjectRow struct {
	ID                 string
	Name               string
	FirstPromptPreview string
	UpdatedAtUnixMs    int64
}

func (q *Queries) ListSessionsByProject(ctx context.Context, projectID string) ([]ListSessionsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByProjectRow
	for rows.Next() {
		var i ListSessionsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FirstPromptPreview,
			&i.UpdatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseActiveRuntimeLeasesBySession = `-- name: ReleaseActiveRuntimeLeasesBySession :exec
UPDATE runtime_leases
SET
    state = 'released',
    released_at_unix_ms = ?1
WHERE session_id = ?2
  AND state = 'active'
`

type ReleaseActiveRuntimeLeasesBySessionParams struct {
	ReleasedAtUnixMs int64
	SessionID        string
}

func (q *Queries) ReleaseActiveRuntimeLeasesBySession(ctx context.Context, arg ReleaseActiveRuntimeLeasesBySessionParams) error {
	_, err := q.db.ExecContext(ctx, releaseActiveRuntimeLeasesBySession, arg.ReleasedAtUnixMs, arg.SessionID)
	return err
}

const releaseRuntimeLeaseByID = `-- name: ReleaseRuntimeLeaseByID :execrows
UPDATE runtime_leases
SET
    state = 'released',
    released_at_unix_ms = ?1
WHERE id = ?2
  AND session_id = ?3
  AND state <> 'released'
`

type ReleaseRuntimeLeaseByIDParams struct {
	ReleasedAtUnixMs int64
	LeaseID          string
	SessionID        string
}

func (q *Queries) ReleaseRuntimeLeaseByID(ctx context.Context, arg ReleaseRuntimeLeaseByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseRuntimeLeaseByID, arg.ReleasedAtUnixMs, arg.LeaseID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProject = `-- name: UpsertProject :exec
INSERT INTO projects (
    id,
    display_name,
    created_at_unix_ms,
    updated_at_unix_ms,
    metadata_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(id) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at_unix_ms = excluded.updated_at_unix_ms,
    metadata_json = excluded.metadata_json
`

type UpsertProjectParams struct {
	ID              string
	DisplayName     string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	MetadataJson    string
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertProject,
		arg.ID,
		arg.DisplayName,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
		arg.MetadataJson,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (
    id,
    project_id,
    workspace_id,
    worktree_id,
    artifact_relpath,
    name,
    first_prompt_preview,
    input_draft,
    parent_session_id,
    created_at_unix_ms,
    updated_at_unix_ms,
    last_sequence,
    model_request_count,
    in_flight_step,
    agents_injected,
    launch_visible,
    cwd_relpath,
    continuation_json,
    locked_json,
    usage_state_json,
    metadata_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21
)
ON CONFLICT(id) DO UPDATE SET
    project_id = excluded.project_id,
    workspace_id = excluded.workspace_id,
    worktree_id = excluded.worktree_id,
    artifact_relpath = excluded.artifact_relpath,
    name = excluded.name,
    first_prompt_preview = excluded.first_prompt_preview,
    input_draft = excluded.input_draft,
    parent_session_id = excluded.parent_session_id,
    updated_at_unix_ms = excluded.updated_at_unix_ms,
    last_sequence = excluded.last_sequence,
    model_request_count = excluded.model_request_count,
    in_flight_step = excluded.in_flight_step,
    agents_injected = excluded.agents_injected,
    launch_visible = CASE
        WHEN sessions.launch_visible <> 0 OR excluded.launch_visible <> 0 THEN 1
        ELSE 0
    END,
    cwd_relpath = excluded.cwd_relpath,
    continuation_json = excluded.continuation_json,
    locked_json = excluded.locked_json,
    usage_state_json = excluded.usage_state_json,
    metadata_json = excluded.metadata_json
`

type UpsertSessionParams struct {
	ID                 string
	ProjectID          string
	WorkspaceID        string
	WorktreeID         sql.NullString
	ArtifactRelpath    string
	Name               string
	FirstPromptPreview string
	InputDraft         string
	ParentSessionID    string
	CreatedAtUnixMs    int64
	UpdatedAtUnixMs    int64
	LastSequence       int64
	ModelRequestCount  int64
	InFlightStep       int64
	AgentsInjected     int64
	LaunchVisible      int64
	CwdRelpath         string
	ContinuationJson   string
	LockedJson         string
	UsageStateJson     string
	MetadataJson       string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.WorktreeID,
		arg.ArtifactRelpath,
		arg.Name,
		arg.FirstPromptPreview,
		arg.InputDraft,
		arg.ParentSessionID,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
		arg.LastSequence,
		arg.ModelRequestCount,
		arg.InFlightStep,
		arg.AgentsInjected,
		arg.LaunchVisible,
		arg.CwdRelpath,
		arg.ContinuationJson,
		arg.LockedJson,
		arg.UsageStateJson,
		arg.MetadataJson,
	)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (
    id,
    project_id,
    canonical_root_path,
    display_name,
    availability,
    is_primary,
    git_metadata_json,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT(id) DO UPDATE SET
    project_id = excluded.project_id,
    canonical_root_path = excluded.canonical_root_path,
    display_name = excluded.display_name,
    availability = excluded.availability,
    is_primary = excluded.is_primary,
    git_metadata_json = excluded.git_metadata_json,
    updated_at_unix_ms = excluded.updated_at_unix_ms
`

type UpsertWorkspaceParams struct {
	ID                string
	ProjectID         string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsPrimary         int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace,
		arg.ID,
		arg.ProjectID,
		arg.CanonicalRootPath,
		arg.DisplayName,
		arg.Availability,
		arg.IsPrimary,
		arg.GitMetadataJson,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}
