// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const getProjectSummary = `-- name: GetProjectSummary :one
SELECT
    p.id,
    p.display_name,
    w.canonical_root_path AS root_path,
    CAST(COALESCE(COUNT(s.id), 0) AS INTEGER) AS session_count,
    COALESCE(MAX(s.updated_at_unix_ms), p.updated_at_unix_ms) AS latest_activity_unix_ms
FROM projects p
JOIN workspaces w ON w.project_id = p.id AND w.is_primary = 1
LEFT JOIN sessions s ON s.project_id = p.id
WHERE p.id = ?1
GROUP BY p.id, p.display_name, w.canonical_root_path, p.updated_at_unix_ms
LIMIT 1
`

type GetProjectSummaryRow struct {
	ID                   string
	DisplayName          string
	RootPath             string
	SessionCount         int64
	LatestActivityUnixMs int64
}

func (q *Queries) GetProjectSummary(ctx context.Context, projectID string) (GetProjectSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectSummary, projectID)
	var i GetProjectSummaryRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.RootPath,
		&i.SessionCount,
		&i.LatestActivityUnixMs,
	)
	return i, err
}

const getWorkspaceBindingByCanonicalRoot = `-- name: GetWorkspaceBindingByCanonicalRoot :one
SELECT
    p.id AS project_id,
    p.display_name AS project_display_name,
    w.id AS workspace_id,
    w.canonical_root_path AS workspace_root
FROM workspaces w
JOIN projects p ON p.id = w.project_id
WHERE w.canonical_root_path = ?1
LIMIT 1
`

type GetWorkspaceBindingByCanonicalRootRow struct {
	ProjectID          string
	ProjectDisplayName string
	WorkspaceID        string
	WorkspaceRoot      string
}

func (q *Queries) GetWorkspaceBindingByCanonicalRoot(ctx context.Context, canonicalRootPath string) (GetWorkspaceBindingByCanonicalRootRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBindingByCanonicalRoot, canonicalRootPath)
	var i GetWorkspaceBindingByCanonicalRootRow
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectDisplayName,
		&i.WorkspaceID,
		&i.WorkspaceRoot,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id,
    p.display_name,
    w.canonical_root_path AS root_path,
    CAST(COALESCE(COUNT(s.id), 0) AS INTEGER) AS session_count,
    COALESCE(MAX(s.updated_at_unix_ms), p.updated_at_unix_ms) AS latest_activity_unix_ms
FROM projects p
JOIN workspaces w ON w.project_id = p.id AND w.is_primary = 1
LEFT JOIN sessions s ON s.project_id = p.id
GROUP BY p.id, p.display_name, w.canonical_root_path, p.updated_at_unix_ms
ORDER BY latest_activity_unix_ms DESC
`

type ListProjectsRow struct {
	ID                   string
	DisplayName          string
	RootPath             string
	SessionCount         int64
	LatestActivityUnixMs int64
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.RootPath,
			&i.SessionCount,
			&i.LatestActivityUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT
    id,
    name,
    first_prompt_preview,
    updated_at_unix_ms
FROM sessions
WHERE project_id = ?1
ORDER BY updated_at_unix_ms DESC, rowid DESC
`

type ListSessionsByProjectRow struct {
	ID                 string
	Name               string
	FirstPromptPreview string
	UpdatedAtUnixMs    int64
}

func (q *Queries) ListSessionsByProject(ctx context.Context, projectID string) ([]ListSessionsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByProjectRow
	for rows.Next() {
		var i ListSessionsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FirstPromptPreview,
			&i.UpdatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :exec
INSERT INTO projects (
    id,
    display_name,
    created_at_unix_ms,
    updated_at_unix_ms,
    metadata_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT(id) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at_unix_ms = excluded.updated_at_unix_ms,
    metadata_json = excluded.metadata_json
`

type UpsertProjectParams struct {
	ID              string
	DisplayName     string
	CreatedAtUnixMs int64
	UpdatedAtUnixMs int64
	MetadataJson    string
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertProject,
		arg.ID,
		arg.DisplayName,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
		arg.MetadataJson,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (
    id,
    project_id,
    workspace_id,
    worktree_id,
    artifact_relpath,
    name,
    first_prompt_preview,
    input_draft,
    parent_session_id,
    created_at_unix_ms,
    updated_at_unix_ms,
    last_sequence,
    model_request_count,
    in_flight_step,
    agents_injected,
    cwd_relpath,
    continuation_json,
    locked_json,
    usage_state_json,
    metadata_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20
)
ON CONFLICT(id) DO UPDATE SET
    project_id = excluded.project_id,
    workspace_id = excluded.workspace_id,
    worktree_id = excluded.worktree_id,
    artifact_relpath = excluded.artifact_relpath,
    name = excluded.name,
    first_prompt_preview = excluded.first_prompt_preview,
    input_draft = excluded.input_draft,
    parent_session_id = excluded.parent_session_id,
    updated_at_unix_ms = excluded.updated_at_unix_ms,
    last_sequence = excluded.last_sequence,
    model_request_count = excluded.model_request_count,
    in_flight_step = excluded.in_flight_step,
    agents_injected = excluded.agents_injected,
    cwd_relpath = excluded.cwd_relpath,
    continuation_json = excluded.continuation_json,
    locked_json = excluded.locked_json,
    usage_state_json = excluded.usage_state_json,
    metadata_json = excluded.metadata_json
`

type UpsertSessionParams struct {
	ID                 string
	ProjectID          string
	WorkspaceID        string
	WorktreeID         sql.NullString
	ArtifactRelpath    string
	Name               string
	FirstPromptPreview string
	InputDraft         string
	ParentSessionID    string
	CreatedAtUnixMs    int64
	UpdatedAtUnixMs    int64
	LastSequence       int64
	ModelRequestCount  int64
	InFlightStep       int64
	AgentsInjected     int64
	CwdRelpath         string
	ContinuationJson   string
	LockedJson         string
	UsageStateJson     string
	MetadataJson       string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.WorktreeID,
		arg.ArtifactRelpath,
		arg.Name,
		arg.FirstPromptPreview,
		arg.InputDraft,
		arg.ParentSessionID,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
		arg.LastSequence,
		arg.ModelRequestCount,
		arg.InFlightStep,
		arg.AgentsInjected,
		arg.CwdRelpath,
		arg.ContinuationJson,
		arg.LockedJson,
		arg.UsageStateJson,
		arg.MetadataJson,
	)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (
    id,
    project_id,
    canonical_root_path,
    display_name,
    availability,
    is_primary,
    git_metadata_json,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT(id) DO UPDATE SET
    project_id = excluded.project_id,
    canonical_root_path = excluded.canonical_root_path,
    display_name = excluded.display_name,
    availability = excluded.availability,
    is_primary = excluded.is_primary,
    git_metadata_json = excluded.git_metadata_json,
    updated_at_unix_ms = excluded.updated_at_unix_ms
`

type UpsertWorkspaceParams struct {
	ID                string
	ProjectID         string
	CanonicalRootPath string
	DisplayName       string
	Availability      string
	IsPrimary         int64
	GitMetadataJson   string
	CreatedAtUnixMs   int64
	UpdatedAtUnixMs   int64
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace,
		arg.ID,
		arg.ProjectID,
		arg.CanonicalRootPath,
		arg.DisplayName,
		arg.Availability,
		arg.IsPrimary,
		arg.GitMetadataJson,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}
